// 메모 시스템 아키텍처 — 정적 데이터(진실의 원천). 시스템 변경 시 이 파일만 갱신.
// 시크릿은 절대 평문 금지 — $VAR 플레이스홀더만.
// 이 파일은 조사 workflow(8개 흐름 병렬 코드 조사) 결과를 정규화해 생성됨.
import type { ArchitectureGraph } from "./types";

export const ARCHITECTURE_GRAPH: ArchitectureGraph = {
  nodes: [
  {
    id: "action-listDueReminders",
    layer: "entities",
    label: "listDueReminders",
    path: "apps/dashboard/src/entities/memo/api/memoActionItemRepo.ts",
    symbol: "listDueReminders",
    role: "리마인더 cron 대상 조회 — status='accepted' + dueAt IS NOT NULL + dueAt≤now + remindedAt IS NULL. memos JOIN으로 push body용 memoTitle 동봉, dueAt asc, limit.",
    keyExports: ["listDueReminders","DueReminderItem","markActionItemReminded"],
    dependsOn: ["table-memo-action-items","table-memos"],
  },
  {
    id: "action-markActionItemReminded",
    layer: "entities",
    label: "markActionItemReminded",
    path: "apps/dashboard/src/entities/memo/api/memoActionItemRepo.ts",
    symbol: "markActionItemReminded",
    role: "🔑 remindedAt claim — UPDATE memo_action_items SET reminded_at=now, updated_at=now WHERE id. push 결과 무관하게 기록해 리마인더가 매시간 무한 재시도로 변하는 것을 방지.",
    keyExports: ["markActionItemReminded"],
    dependsOn: ["table-memo-action-items"],
  },
  {
    id: "action-remindDueActionItem",
    layer: "features",
    label: "remindDueActionItem",
    path: "apps/dashboard/src/features/memo-actions/api/remindDueActions.ts",
    symbol: "remindDueActionItem",
    role: "per-target 발송 — sendPushToUser로 ⏰ push 발송 후 markActionItemReminded로 remindedAt 기록. push 실패·구독 없음·VAPID 미설정이어도 기록해 무한 재시도 차단.",
    keyExports: ["remindDueActionItem","RemindDueResult"],
    dependsOn: ["action-markActionItemReminded","shared-sendPushToUser"],
    warning: "⚠️ push(비가역) 발송 뒤 markActionItemReminded는 반드시 별도 try(best-effort). 같은 try면 mark 실패가 push 성공을 error로 가려 다음 주기 double-send (PR #157 관례).",
  },
  {
    id: "actions-extractAndPersistMemoActions",
    layer: "features",
    label: "extractAndPersistMemoActions",
    path: "apps/dashboard/src/features/memo-actions/api/extractMemoActions.ts",
    symbol: "extractAndPersistMemoActions",
    role: "메모 → 할일·일정 구조화 추출 코어. EXTRACT_MODEL=claude-sonnet-5로 analyzeStructured 호출, ActionExtractionSchema safeParse 후 insertActionItemsAndMark 위임. 결과는 항상 proposed (자동 등록 없음)",
    keyExports: ["extractAndPersistMemoActions","ExtractActionsResult","ActionExtractionSchema"],
    dependsOn: ["actions-insertActionItemsAndMark","memo-dates-lib"],
    warning: "actionsExtractedAt !== null이면 already-extracted 조기 반환. LLM 실패는 마커 미기록 후 llm-unavailable 반환 → cron sweep이 재시도. 상대 날짜 해석 품질 필요 — haiku 부적합이라 sonnet 고정",
  },
  {
    id: "actions-insertActionItemsAndMark",
    layer: "entities",
    label: "insertActionItemsAndMark",
    path: "apps/dashboard/src/entities/memo/api/memoActionItemRepo.ts",
    symbol: "insertActionItemsAndMark",
    role: "추출 결과 삽입 + memos.actions_extracted_at 마킹을 단일 트랜잭션 claim-first로 수행. 마킹(IS NULL 조건부 UPDATE)을 먼저 실행해 승자만 insert, 0-row면 null 반환",
    keyExports: ["insertActionItemsAndMark","NewActionItem","listActionItemsByUser"],
    dependsOn: ["table-memo-action-items","table-memos"],
    warning: "claim-first 순서 필수 — 마킹을 IS NULL 조건부 UPDATE로 먼저 실행해 승자만 insert. 뒤집으면 after() 추출과 cron sweep 동시 실행이 제안을 중복 삽입 (row lock이 두 트랜잭션 직렬화, 패자는 0-row skip)",
  },
  {
    id: "actions-MemoActionPanel",
    layer: "features",
    label: "MemoActionPanel",
    path: "apps/dashboard/src/features/memo-actions/ui/MemoActionPanel.tsx",
    symbol: "MemoActionPanel",
    role: "액션 제안·할일 패널 client UI — proposed엔 수락/무시, accepted엔 완료/무시 버튼을 렌더하고 클릭 시 updateActionItemStatusAction을 호출한다(로컬 목록 상태 없이 revalidate에 의존).",
    keyExports: ["MemoActionPanel"],
    dependsOn: ["actions-updateActionItemStatusAction","memo-manage-MemoList"],
  },
  {
    id: "actions-updateActionItemStatusAction",
    layer: "features",
    label: "updateActionItemStatusAction",
    path: "apps/dashboard/src/features/memo-actions/api/actionItemActions.ts",
    symbol: "updateActionItemStatusAction",
    role: "상태 전이 Server Action — 세션 인증 후 목적지를 accepted|dismissed|done 3종으로 제한 검증, updateActionItemStatus 호출 후 성공 시 revalidatePath('/memos'). null 반환은 not-found로 수렴.",
    keyExports: ["updateActionItemStatusAction","ActionItemStatusUpdate","UpdateActionItemResult"],
    dependsOn: ["repo-updateActionItemStatus"],
    warning: "user 트리거·no-LLM 흐름. proposed로의 전이는 존재하지 않아 목적지 유니온에서 배제됨.",
  },
  {
    id: "anthropic-HAIKU_MODEL",
    layer: "shared",
    label: "HAIKU_MODEL / gatewayDefaults",
    path: "apps/dashboard/src/shared/lib/llm/anthropic.ts",
    symbol: "HAIKU_MODEL",
    role: "분류에 쓰는 Haiku 모델 ID(claude-haiku-4-5-*)+ llm-gateway 프록시 기본 옵션(provider claude-cli)+ logLlmSpend 토큰 로깅",
    keyExports: ["HAIKU_MODEL","gatewayDefaults","logLlmSpend"],
  },
  {
    id: "category-isValidCategorySlug",
    layer: "entities",
    label: "isValidCategorySlug",
    path: "apps/dashboard/src/entities/memo/model/category.ts",
    symbol: "isValidCategorySlug",
    role: "slug 형식 검증(CATEGORY_SLUG_RE = /^[a-z][a-z0-9-]{0,39}$/) — LLM 응답 파싱 뒤 방어 재검증, 실패 시 'etc' 강등",
    keyExports: ["isValidCategorySlug","CATEGORY_SLUG_RE","SEED_MEMO_CATEGORIES","SEED_CATEGORY_LABELS","MemoCategory"],
  },
  {
    id: "category-SEED_MEMO_CATEGORIES",
    layer: "entities",
    label: "SEED_MEMO_CATEGORIES",
    path: "apps/dashboard/src/entities/memo/model/category.ts",
    symbol: "SEED_MEMO_CATEGORIES",
    role: "시드 6종 카테고리(id+labelKo) — DB 태그 조회 실패 시 프롬프트 주입 폴백(최소 재사용 보장)",
    keyExports: ["SEED_MEMO_CATEGORIES","SEED_CATEGORY_LABELS"],
  },
  {
    id: "classify-classifyAndPersistMemoCategory",
    layer: "entities",
    label: "classifyAndPersistMemoCategory",
    path: "apps/dashboard/src/entities/memo/api/classifyMemo.ts",
    symbol: "classifyAndPersistMemoCategory",
    role: "메모 분류+영속화 오케스트레이션 — 멱등(category!==null 이면 already-classified skip), LLM 결과를 upsertCategory→setMemoCategory 순으로 커밋",
    keyExports: ["classifyAndPersistMemoCategory","classifyMemoContent","MemoCategoryResponseSchema","ClassifyAndPersistResult"],
    dependsOn: ["category-isValidCategorySlug","classify-classifyMemoContent","classify-upsertCategory","memo-setMemoCategory"],
    warning: "🔑 category IS NULL 멱등 — 이미 분류된 행은 LLM 미호출 skip. upsertCategory 가 setMemoCategory 보다 먼저(FK 위반 방지). slug 방어 재검증: isValidCategorySlug 실패 시 'etc'/'기타' 로 강등",
  },
  {
    id: "classify-classifyMemoContent",
    layer: "entities",
    label: "classifyMemoContent",
    path: "apps/dashboard/src/entities/memo/api/classifyMemo.ts",
    symbol: "classifyMemoContent",
    role: "Haiku 로 메모 본문 1건 분류 — 기존 태그 목록을 시스템 프롬프트에 주입, analyzeStructured 로 {category,labelKo} 획득. 실패는 typed llm-unavailable 반환",
    keyExports: ["classifyMemoContent","MemoCategoryResponseSchema","ClassifyMemoContentResult"],
    dependsOn: ["anthropic-HAIKU_MODEL","category-SEED_MEMO_CATEGORIES","search-listCategories"],
    warning: "🔑 MemoCategoryResponseSchema 에 category slug regex 금지 — analyzeStructured 가 스키마 위반 시 throw→catch 에서 llm-unavailable 로 잡혀 etc fallback 에 도달 못 하고 영원히 미분류·cron 무한 재시도 (커밋 5699622). 형식 검증은 파싱 뒤 isValidCategorySlug 로 수행",
  },
  {
    id: "classify-upsertCategory",
    layer: "entities",
    label: "upsertCategory",
    path: "apps/dashboard/src/entities/memo/api/categoryRepo.ts",
    symbol: "upsertCategory",
    role: "새 태그를 memo_categories 에 사전 등록 — onConflictDoNothing(id). setMemoCategory FK 참조 전에 태그 존재를 보장",
    keyExports: ["upsertCategory","listCategories","MemoCategoryRow"],
    dependsOn: ["table-memo-categories"],
  },
  {
    id: "compose-cleanupTranscript",
    layer: "features",
    label: "cleanupTranscript",
    path: "apps/dashboard/src/features/memo-compose/lib/cleanup-transcript.ts",
    symbol: "cleanupTranscript",
    role: "받아쓰기 원문→AI 정리(transcript normalizer). Sonnet(claude-sonnet-5) 호출, 실패·과축약·거절·초과길이는 raw-fallback",
    keyExports: ["cleanupTranscript","CleanupResponseSchema","isDegenerateCleanup","CleanupResult"],
  },
  {
    id: "compose-cleanupTranscriptAction",
    layer: "features",
    label: "cleanupTranscriptAction",
    path: "apps/dashboard/src/features/memo-compose/api/cleanupTranscriptAction.ts",
    symbol: "cleanupTranscriptAction",
    role: "\"use server\" — auth 후 cleanupTranscript 위임하는 AI 정리 RPC 경계",
    keyExports: ["cleanupTranscriptAction"],
    dependsOn: ["compose-cleanupTranscript"],
    warning: "\"use server\" 파일에서 import 타입의 export type 재-export 금지 — server-action 변환이 런타임 참조를 만들어 ReferenceError로 모듈 사망",
  },
  {
    id: "compose-createMemoAction",
    layer: "features",
    label: "createMemoAction",
    path: "apps/dashboard/src/features/memo-compose/api/createMemoAction.ts",
    symbol: "createMemoAction",
    role: "메모 저장 Server Action — 저장 성공 후 after()로 분류·액션추출을 백그라운드 실행하는 after() 트리거 진입점",
    keyExports: ["createMemoAction","CreateMemoInputAction","CreateMemoActionResult"],
    dependsOn: ["actions-extractAndPersistMemoActions","classify-classifyAndPersistMemoCategory","memo-createMemo"],
    warning: "액션 추출은 after() 백그라운드 — 클라이언트 Server Action 직렬 큐를 LLM 지연만큼 점유하지 않게 (리뷰 확정 결함). classify와 allSettled 병렬·독립",
  },
  {
    id: "compose-MemoComposer",
    layer: "features",
    label: "MemoComposer",
    path: "apps/dashboard/src/features/memo-compose/ui/MemoComposer.tsx",
    symbol: "MemoComposer",
    role: "\"use client\" 작성 UI — 음성 받아쓰기+정리 요청+승인 저장. client 배럴 경유로만 Server Action 호출",
    keyExports: ["MemoComposer"],
    dependsOn: ["compose-cleanupTranscriptAction","compose-createMemoAction"],
  },
  {
    id: "cron-memo-action-reminders",
    layer: "app",
    label: "cron/memo-action-reminders/route.ts",
    path: "apps/dashboard/src/app/api/cron/memo-action-reminders/route.ts",
    symbol: "POST",
    role: "리마인더 cron 엔드포인트. createCronHandler로 대상 select+per-target 발송을 조립 (no-LLM, SWEEP_LIMIT=100, concurrency=2).",
    keyExports: ["POST","dynamic"],
    dependsOn: ["action-listDueReminders","action-remindDueActionItem","shared-createCronHandler"],
  },
  {
    id: "cron-memo-classify",
    layer: "app",
    label: "cron/memo-classify",
    path: "apps/dashboard/src/app/api/cron/memo-classify/route.ts",
    symbol: "POST",
    role: "매시간 KST 미분류 메모 LLM 분류 sweep 진입점 — createCronHandler 로 targetSelect=listUnclassifiedMemos(50), perTarget=classifyAndPersistMemoCategory, concurrency=2",
    keyExports: ["POST","dynamic"],
    dependsOn: ["classify-classifyAndPersistMemoCategory","memo-listUnclassifiedMemos","shared-createCronHandler"],
    warning: "⏰ cron 진입. SWEEP_LIMIT=50건/회. 🔑 llm-unavailable 결과를 throw로 승격해 envelope failed 카운트로 관측 — 행은 category NULL 유지되어 다음 주기 자연 재시도",
  },
  {
    id: "cron-memo-digest",
    layer: "app",
    label: "cron/memo-digest/route.ts",
    path: "apps/dashboard/src/app/api/cron/memo-digest/route.ts",
    symbol: "POST",
    role: "매일 19:05 KST 트리거되는 주간 다이제스트 cron 라우트 — 메모 보유 사용자 전체를 대상으로 generateWeeklyDigest 실행 (concurrency 2).",
    keyExports: ["POST","dynamic"],
    dependsOn: ["digest-generateWeeklyDigest","digest-listMemoAuthorUserIds","shared-createCronHandler"],
    warning: "⏰ 매일 19:05 발화하되 due 판정은 feature 레이어 — 일요일 19:00 이후만 실제 생성, 놓친 날은 다음 날 catchup. LLM 실패는 perTarget throw로 envelope error 격리.",
  },
  {
    id: "cron-memo-extract-actions",
    layer: "app",
    label: "cron/memo-extract-actions",
    path: "apps/dashboard/src/app/api/cron/memo-extract-actions/route.ts",
    symbol: "POST",
    role: "매시간 41분 KST cron sweep — 48h 창 내 미추출 메모 액션 추출 (after() 실패 안전망). createCronHandler로 concurrency 2, SWEEP_LIMIT 50",
    keyExports: ["POST","dynamic"],
    dependsOn: ["actions-extractAndPersistMemoActions","memo-listMemosNeedingExtraction"],
    warning: "LLM 실패는 llm-unavailable을 throw로 변환해 status=error 격리 → 마커 미기록 → 다음 주기 재시도 (48h 창 내). 과거 백필 없음",
  },
  {
    id: "digest-computeDigestWindow",
    layer: "features",
    label: "computeDigestWindow",
    path: "apps/dashboard/src/features/memo-digest/lib/week.ts",
    symbol: "computeDigestWindow",
    role: "현재 시각 기준 다이제스트 창 산출 — KST 고정 UTC+9로 [직전 일요일 19:00, 대상 일요일 19:00) 반개구간과 weekEnd 계산.",
    keyExports: ["computeDigestWindow","windowForWeekEnd","formatWeekLabel","DigestWindow"],
  },
  {
    id: "digest-enumerateMissingWeekEnds",
    layer: "features",
    label: "enumerateMissingWeekEnds",
    path: "apps/dashboard/src/features/memo-digest/lib/week.ts",
    symbol: "enumerateMissingWeekEnds",
    role: "백필 경로 — 마지막 기록 주 이후 누락된 weekEnd를 오래된 순으로 최대 maxWeeks개 열거 (lastWeekEnd=null이면 현재 주만).",
    keyExports: ["enumerateMissingWeekEnds"],
    warning: "⚠️ 반드시 오래된 순(reverse 후 slice)으로 잘라야 한다 — 최신 우선 컷이면 커서(getLatestDigest=max week_end)가 배치 후 구멍을 건너뛰어 maxWeeks(4주)보다 긴 공백의 잔여 주가 영구 스킵됨 (PR #297, Codex 리뷰 확정 결함).",
  },
  {
    id: "digest-generateWeeklyDigest",
    layer: "features",
    label: "generateWeeklyDigest",
    path: "apps/dashboard/src/features/memo-digest/api/generateWeeklyDigest.ts",
    symbol: "generateWeeklyDigest",
    role: "주간 다이제스트 오케스트레이션 — due 판정 + 누락 주 백필(최대 4주)을 오래된 순으로 순회하며 창별 생성, 최신 주만 push 발송.",
    keyExports: ["generateWeeklyDigest","GenerateDigestResult","DigestSummarySchema","DIGEST_MODEL"],
    dependsOn: ["digest-computeDigestWindow","digest-enumerateMissingWeekEnds","digest-getLatestDigest","digest-hasDigest","digest-insertDigest","digest-listMemosBetween","digest-listMemosOlderThan","digest-pickResurfaced","shared-analyzeStructured","shared-sendPushToUser","table-memo-weekly-digests"],
    warning: "🔑 요약 모델 DIGEST_MODEL=claude-sonnet-5 (Sonnet) — 생성 작업이라 haiku 부적합(이메일 초안 거절 전례). 순서 계약: LLM 성공 → 멱등 insert → push best-effort. LLM 실패는 throw로 행 미삽입 → 다음 날 재시도.",
  },
  {
    id: "digest-getLatestDigest",
    layer: "entities",
    label: "getLatestDigest",
    path: "apps/dashboard/src/entities/memo/api/memoDigestRepo.ts",
    symbol: "getLatestDigest",
    role: "백필 커서 — 사용자의 가장 최근 week_end(max) digest 행 조회. enumerateMissingWeekEnds의 시작점.",
    keyExports: ["getLatestDigest"],
    dependsOn: ["table-memo-weekly-digests"],
  },
  {
    id: "digest-hasDigest",
    layer: "entities",
    label: "hasDigest",
    path: "apps/dashboard/src/entities/memo/api/memoDigestRepo.ts",
    symbol: "hasDigest",
    role: "창 중복 가드 — (userId, weekEnd) 조합의 digest 존재 여부 조회 (재생성 방지).",
    keyExports: ["hasDigest"],
    dependsOn: ["table-memo-weekly-digests"],
  },
  {
    id: "digest-insertDigest",
    layer: "entities",
    label: "insertDigest",
    path: "apps/dashboard/src/entities/memo/api/memoDigestRepo.ts",
    symbol: "insertDigest",
    role: "멱등 삽입 — onConflictDoNothing으로 unique(user_id, week_end) 충돌 시 null 반환 (동시 실행 이중 push 방어).",
    keyExports: ["insertDigest","InsertDigestInput"],
    dependsOn: ["table-memo-weekly-digests"],
  },
  {
    id: "digest-listMemoAuthorUserIds",
    layer: "entities",
    label: "listMemoAuthorUserIds",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "listMemoAuthorUserIds",
    role: "다이제스트 cron 대상 select — memos 테이블에서 메모를 1건이라도 가진 사용자 id를 distinct 조회.",
    keyExports: ["listMemoAuthorUserIds"],
    dependsOn: ["table-memos"],
  },
  {
    id: "digest-listMemosBetween",
    layer: "entities",
    label: "listMemosBetween",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "listMemosBetween",
    role: "다이제스트 창 조회 — [from,to) 반개구간 사용자 메모를 오래된 순으로 최대 500건 로드 (요약 입력).",
    keyExports: ["listMemosBetween"],
    dependsOn: ["table-memos"],
  },
  {
    id: "digest-listMemosOlderThan",
    layer: "entities",
    label: "listMemosOlderThan",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "listMemosOlderThan",
    role: "재부상 후보 조회 — cutoff(30일) 이전 생성 메모 전체를 오래된 순으로 최대 2000건 로드.",
    keyExports: ["listMemosOlderThan"],
    dependsOn: ["table-memos"],
  },
  {
    id: "digest-pickResurfaced",
    layer: "features",
    label: "pickResurfaced",
    path: "apps/dashboard/src/features/memo-digest/lib/resurface.ts",
    symbol: "pickResurfaced",
    role: "오래된 메모 재부상 선정 — 30일 이상 후보에서 나이 비례 가중 무작위로 최대 2개 비복원 추출 (rng 주입 가능).",
    keyExports: ["pickResurfaced","RESURFACE_MIN_AGE_DAYS","RESURFACE_COUNT"],
  },
  {
    id: "memo-actionItem-stateMachine",
    layer: "entities",
    label: "ACTION_ITEM_ALLOWED_FROM",
    path: "apps/dashboard/src/entities/memo/model/actionItem.ts",
    symbol: "ACTION_ITEM_ALLOWED_FROM",
    role: "액션 아이템 상태 기계 단일 정의(client-safe) — proposed→accepted, accepted→done, proposed·accepted→dismissed. dismissed/done은 종단. canTransition/isActionItemStatus 헬퍼와 ACTION_ITEM_STATUSES 상수를 함께 노출하며 UI·Server Action·repo WHERE 절이 공유한다.",
    keyExports: ["ACTION_ITEM_ALLOWED_FROM","ACTION_ITEM_STATUSES","ACTION_ITEM_KINDS","ACTION_ITEM_KIND_LABELS","canTransition","isActionItemStatus","isActionItemKind","ActionItemStatus","ActionItemKind"],
    dependsOn: ["table-memo-action-items"],
    warning: "DB CHECK(memo_action_items_status_check)와 반드시 동기 유지 — 상태 추가 시 스키마 CHECK·테스트 fixture를 전수 grep해야 한다(파일 상단 주석이 명시).",
  },
  {
    id: "memo-createMemo",
    layer: "entities",
    label: "createMemo",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "createMemo",
    role: "메모 행 INSERT(category NULL 로 저장) — 저장 직후 분류/추출이 이 행을 대상으로 트리거됨",
    keyExports: ["createMemo","CreateMemoInput","listMemos","getMemo","setMemoCategory","listUnclassifiedMemos","listMemosNeedingExtraction"],
    dependsOn: ["table-memos"],
  },
  {
    id: "memo-dates-lib",
    layer: "features",
    label: "dates (formatKstNowLabel/parseDueAtIso)",
    path: "apps/dashboard/src/features/memo-actions/lib/dates.ts",
    symbol: "parseDueAtIso",
    role: "KST 현재 라벨 포맷 + LLM이 반환한 dueAtIso 문자열 → Date 파싱 (실패는 null 강등, 제안은 유지)",
    keyExports: ["formatKstNowLabel","parseDueAtIso","formatDueLabel"],
  },
  {
    id: "memo-getDefaultMemoModel",
    layer: "entities",
    label: "getDefaultMemoModel",
    path: "apps/dashboard/src/entities/memo/api/memoPresetRepo.ts",
    symbol: "getDefaultMemoModel",
    role: "사용자 전체 기본 변환 모델 조회 — 행 없으면 claude로 폴백(마이그레이션 전 동작 보존)",
    keyExports: ["getDefaultMemoModel","upsertDefaultMemoModel"],
    dependsOn: ["table-memo-transform-settings"],
  },
  {
    id: "memo-getMemo",
    layer: "entities",
    label: "getMemo",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "getMemo",
    role: "소유자 스코프로 단일 메모 조회 — 변환 입력(cleanedContent) 로드",
    keyExports: ["getMemo"],
    dependsOn: ["table-memos"],
  },
  {
    id: "memo-getPresetBySlug",
    layer: "entities",
    label: "getPresetBySlug",
    path: "apps/dashboard/src/entities/memo/api/memoPresetRepo.ts",
    symbol: "getPresetBySlug",
    role: "(user, slug) 프리셋 override/커스텀 행 조회 — 없으면 코드 기본값 사용",
    keyExports: ["getPresetBySlug","listPresetsByUser","getDefaultMemoModel","upsertPreset"],
    dependsOn: ["table-memo-transform-presets"],
  },
  {
    id: "memo-listMemosNeedingExtraction",
    layer: "entities",
    label: "listMemosNeedingExtraction",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "listMemosNeedingExtraction",
    role: "cron sweep 대상 조회 — actions_extracted_at IS NULL AND created_at >= now-48h, created_at asc, limit 50",
    keyExports: ["listMemosNeedingExtraction"],
    dependsOn: ["table-memos"],
    warning: "과거 백필 없음 — 오래된 메모의 상대 날짜는 기준점이 어긋나 쓰레기 제안만 생성 (분류 backfill과 의도적으로 다른 결정, 스펙 §3)",
  },
  {
    id: "memo-listPresetsByUser",
    layer: "entities",
    label: "listPresetsByUser",
    path: "apps/dashboard/src/entities/memo/api/memoPresetRepo.ts",
    symbol: "listPresetsByUser",
    role: "사용자의 모든 프리셋 override·커스텀 행 조회(createdAt 순)",
    keyExports: ["listPresetsByUser"],
    dependsOn: ["table-memo-transform-presets"],
  },
  {
    id: "memo-listTransformationsByUser",
    layer: "entities",
    label: "listTransformationsByUser",
    path: "apps/dashboard/src/entities/memo/api/memoTransformRepo.ts",
    symbol: "listTransformationsByUser",
    role: "소유자 메모들의 변환본 전체를 memos JOIN으로 1쿼리 로드(N+1 회피)",
    keyExports: ["listTransformationsByUser"],
    dependsOn: ["table-memo-transformations","table-memos"],
  },
  {
    id: "memo-listUnclassifiedMemos",
    layer: "entities",
    label: "listUnclassifiedMemos",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "listUnclassifiedMemos",
    role: "cron sweep 대상 조회 — 전 사용자 category IS NULL 메모를 오래된 순(createdAt asc)으로 limit 건 반환(백필이 과거부터)",
    keyExports: ["listUnclassifiedMemos"],
    dependsOn: ["table-memos"],
  },
  {
    id: "memo-manage-MemoList",
    layer: "features",
    label: "MemoList",
    path: "apps/dashboard/src/features/memo-manage/ui/MemoList.tsx",
    symbol: "MemoList",
    role: "메모 카드 목록 client 컴포넌트 — 각 메모의 액션 아이템이 있으면 MemoActionPanel을 렌더한다.",
    keyExports: ["MemoList"],
    dependsOn: ["page-memos"],
    warning: "features→features import 는 의도적 허용 예외(검색이 목록 렌더를 재사용) — entities 간 직접 참조 금지와 구분.",
  },
  {
    id: "memo-setMemoCategory",
    layer: "entities",
    label: "setMemoCategory",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "setMemoCategory",
    role: "memos.category 컬럼에 확정 slug UPDATE — 분류 결과 영속화(FK 대상 태그는 upsertCategory 로 선등록됨)",
    keyExports: ["setMemoCategory"],
    dependsOn: ["table-memos"],
  },
  {
    id: "memo-upsertTransformation",
    layer: "entities",
    label: "upsertTransformation",
    path: "apps/dashboard/src/entities/memo/api/memoTransformRepo.ts",
    symbol: "upsertTransformation",
    role: "변환본 저장 — memo당 preset당 1개, UNIQUE(memo_id, preset) onConflictDoUpdate로 교체",
    keyExports: ["upsertTransformation","listTransformationsByUser","UpsertTransformationInput"],
    dependsOn: ["table-memo-transformations"],
  },
  {
    id: "memoRepo-listMemos",
    layer: "entities",
    label: "listMemos",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "listMemos",
    role: "원본 메모 목록 repo — user_id 스코프, createdAt desc, LIST_MEMOS_LIMIT=200 상한. 빈 쿼리(비활성) 상태에서 SearchableMemoList 가 렌더하는 기본 목록.",
    keyExports: ["listMemos"],
    dependsOn: ["table-memos"],
  },
  {
    id: "memoRepo-searchMemos",
    layer: "entities",
    label: "searchMemos",
    path: "apps/dashboard/src/entities/memo/api/memoRepo.ts",
    symbol: "searchMemos",
    role: "메모 검색 repo — 토큰별 title·rawContent·cleanedContent ILIKE OR + memo_transformations.content exists() 서브쿼리, 토큰 간 AND, user_id 스코프, createdAt desc, SEARCH_MEMOS_LIMIT+1 조회로 truncated 판별.",
    keyExports: ["searchMemos","SearchMemosOutput","listMemos","setMemoCategory"],
    dependsOn: ["search-tokenizeSearchQuery","table-memo-transformations","table-memos"],
    warning: "인덱스 없이 user_id 필터 후 ILIKE — 개인 규모(수백 행) 전제. 절단은 LIMIT+1 센티널(rows.length > 50)로 판별해 정확히 50개일 때 거짓 절단 안내를 피한다.",
  },
  {
    id: "page-memos",
    layer: "app",
    label: "/memos page",
    path: "apps/dashboard/src/app/(dashboard)/memos/page.tsx",
    symbol: "MemosPage",
    role: "메모 페이지 RSC — listActionItemsByUser로 proposed·accepted 액션을 memoId별로 묶어 MemoList에 내려보내고 revalidatePath('/memos') 대상이 된다.",
    keyExports: ["default","MemosPage (default)","dynamic","MemosPage","default (MemosPage)"],
    dependsOn: ["memo-listTransformationsByUser","memoRepo-listMemos","repo-listActionItemsByUser","search-listCategories","transform-listPresetCatalog","widget-memo"],
    warning: "카테고리 필터는 SQL 이 아니라 listCategories() 로 전체 태그를 내려주고 클라이언트에서 필터링한다 — 페이지는 memos↔memo_categories 를 JOIN 하지 않는다.",
  },
  {
    id: "repo-listActionItemsByUser",
    layer: "entities",
    label: "listActionItemsByUser",
    path: "apps/dashboard/src/entities/memo/api/memoActionItemRepo.ts",
    symbol: "listActionItemsByUser",
    role: "패널 표시용 조회 repo — userId 스코프 + status inArray로 memo_action_items를 createdAt 오름차순 조회. 페이지는 proposed·accepted만 넘겨 dismissed/done을 숨긴다(스펙 §5).",
    keyExports: ["listActionItemsByUser"],
    dependsOn: ["table-memo-action-items"],
  },
  {
    id: "repo-updateActionItemStatus",
    layer: "entities",
    label: "updateActionItemStatus",
    path: "apps/dashboard/src/entities/memo/api/memoActionItemRepo.ts",
    symbol: "updateActionItemStatus",
    role: "상태 전이 repo — ACTION_ITEM_ALLOWED_FROM[to]로 허용 출발 상태를 조회하고, UPDATE WHERE에 id+소유권(userId)+inArray(allowedFrom)을 함께 강제해 불법 전이·타인 항목·동시 전이 경합을 모두 0-row(null)로 수렴시킨다.",
    keyExports: ["updateActionItemStatus","listActionItemsByUser","insertActionItemsAndMark","listDueReminders","markActionItemReminded"],
    dependsOn: ["memo-actionItem-stateMachine","table-memo-action-items"],
  },
  {
    id: "scheduler-memo-action-reminders",
    layer: "app",
    label: "scheduler.js (37분 cron)",
    path: "apps/cron/scheduler.js",
    symbol: "cron.schedule(\"37 * * * *\")",
    role: "매시간 37분 KST에 node-cron이 /api/cron/memo-action-reminders를 HTTP POST로 호출 (23분 memo-classify와 stagger).",
  },
  {
    id: "search-listCategories",
    layer: "entities",
    label: "listCategories",
    path: "apps/dashboard/src/entities/memo/api/categoryRepo.ts",
    symbol: "listCategories",
    role: "등록 카테고리 전체 조회 repo — is_seed desc, created_at asc 정렬. 필터 칩·라벨 조회용으로 페이지가 서버 로드(JOIN 없이 단독 SELECT).",
    keyExports: ["listCategories","upsertCategory","MemoCategoryRow"],
    dependsOn: ["table-memo-categories"],
  },
  {
    id: "search-SearchableMemoList",
    layer: "features",
    label: "SearchableMemoList",
    path: "apps/dashboard/src/features/memo-search/ui/SearchableMemoList.tsx",
    symbol: "SearchableMemoList",
    role: "검색바 + 카테고리 필터 칩 client 컴포넌트 — 300ms 디바운스로 searchMemosAction 호출, 카테고리 필터는 client 측 filterByCategory 로 적용, truncated 시 '최근 50개만 표시' 안내.",
    keyExports: ["SearchableMemoList"],
    dependsOn: ["memo-manage-MemoList","search-searchMemosAction","search-tokenizeSearchQuery"],
    warning: "카테고리 필터는 서버 쿼리가 아닌 client 측 list.filter((m) => m.category === category) — 검색 결과·원본 목록 모두 화면에 보이는 배열에만 적용된다 (SQL WHERE 아님).",
  },
  {
    id: "search-searchMemosAction",
    layer: "features",
    label: "searchMemosAction",
    path: "apps/dashboard/src/features/memo-search/api/searchMemosAction.ts",
    symbol: "searchMemosAction",
    role: "읽기 전용 검색 Server Action — auth 가드 후 searchMemos 위임, 빈 쿼리는 빈 결과 단락, 실패 시 {kind:'failed'} 유니온 반환 (revalidate 없음).",
    keyExports: ["searchMemosAction","SearchMemosResult"],
    dependsOn: ["memoRepo-searchMemos"],
    warning: "\"use server\" + \"server-only\" 이라 client 는 반드시 features/memo-search/client.ts 배럴 경유로만 import (server/client seam).",
  },
  {
    id: "search-tokenizeSearchQuery",
    layer: "entities",
    label: "tokenizeSearchQuery / SEARCH_MEMOS_LIMIT",
    path: "apps/dashboard/src/entities/memo/model/search.ts",
    symbol: "tokenizeSearchQuery",
    role: "검색 쿼리 파싱 순수 모듈 — 공백 분리 AND 토큰(중복 제거·최대 8개·100자 컷) + escapeLike ILIKE 메타문자 이스케이프 + SEARCH_MEMOS_LIMIT=50 상수. server repo 와 client 하이라이트가 공유.",
    keyExports: ["tokenizeSearchQuery","escapeLike","SEARCH_MEMOS_LIMIT","SEARCH_QUERY_MAX_LEN","SEARCH_MAX_TOKENS"],
  },
  {
    id: "shared-analyzeStructured",
    layer: "shared",
    label: "analyzeStructured (llm-gateway)",
    path: "apps/dashboard/src/shared/lib/llm/anthropic.ts",
    symbol: "gatewayDefaults",
    role: "LLM 구조화 호출 게이트웨이 — @krdn/llm-gateway analyzeStructured에 gatewayDefaults(provider claude-cli, cli-proxy baseUrl) 주입, logLlmSpend로 사용량 기록.",
    keyExports: ["gatewayDefaults","logLlmSpend"],
    warning: "provider는 반드시 \"claude-cli\" — \"anthropic\"이면 /v1 경로 누락→404",
  },
  {
    id: "shared-createCronHandler",
    layer: "shared",
    label: "createCronHandler",
    path: "apps/dashboard/src/shared/lib/cron/createCronHandler.ts",
    symbol: "createCronHandler",
    role: "cron route factory — verifyCronBearer → targetSelect → per-target 격리 실행 → envelope JSON 반환. targetSelect throw는 500, per-target throw는 results[].status='error'로 격리.",
    keyExports: ["createCronHandler","CronHandlerDefinition"],
  },
  {
    id: "shared-sendPushToUser",
    layer: "shared",
    label: "sendPushToUser",
    path: "apps/dashboard/src/shared/lib/push/index.ts",
    symbol: "sendPushToUser",
    role: "userId의 전 push_subscriptions에 web-push VAPID 직렬 발송 + 만료(404/410) 구독 정리. 구독 0건은 에러 아님(total=0 조용히 반환).",
    keyExports: ["sendPushToUser","sendPush","PushPayload","SendPushToUserResult"],
    dependsOn: ["table-push-subscriptions"],
  },
  {
    id: "table-memo-action-items",
    layer: "shared",
    label: "memo_action_items",
    path: "apps/dashboard/src/shared/lib/db/schema/memo.ts",
    symbol: "memoActionItems",
    role: "메모에서 LLM 추출한 할일·일정 제안 테이블. dueAt(기한, null=리마인더 없음)·remindedAt(발송 claim)·status(proposed/accepted/dismissed/done)·kind(todo/event). user_id 비정규화로 cron이 memo JOIN 없이 사용자 스코프 질의.",
    keyExports: ["memoActionItems"],
    dependsOn: ["table-memos"],
    warning: "status CHECK 제약과 코드 상태 기계(ACTION_ITEM_ALLOWED_FROM)가 이중 정의 — 한쪽만 바꾸면 drift. 상태 추가 시 DDL CHECK와 코드를 함께 갱신.",
  },
  {
    id: "table-memo-categories",
    layer: "shared",
    label: "memo_categories",
    path: "apps/dashboard/src/shared/lib/db/schema/memo.ts",
    symbol: "memoCategories",
    role: "카테고리 태그 사전 테이블 — id(slug PK)·label_ko·is_seed. 고정 enum 아닌 행 관리로 LLM 분류 시 upsert 되어 코드 없이 태그 증가. memos.category 의 FK 대상.",
    keyExports: ["memoCategories"],
    warning: "CHECK memo_categories_slug_format 이 slug 형식을 DB 레벨에서도 강제 — upsertCategory 전에 코드에서 isValidCategorySlug 로 걸러야 INSERT throw 회피",
  },
  {
    id: "table-memo-transform-presets",
    layer: "shared",
    label: "memo_transform_presets",
    path: "apps/dashboard/src/shared/lib/db/schema/memo.ts",
    symbol: "memoTransformPresets",
    role: "빌트인 override(slug=빌트인 id)+커스텀 프리셋 — model(claude/codex/gemini, null=상속)·modelId(프록시 정확 ID)",
    keyExports: ["memoTransformPresets"],
  },
  {
    id: "table-memo-transform-settings",
    layer: "shared",
    label: "memo_transform_settings",
    path: "apps/dashboard/src/shared/lib/db/schema/memo.ts",
    symbol: "memoTransformSettings",
    role: "사용자별 전체 기본 변환 모델(defaultModel/defaultModelId) — 행 없으면 claude로 해석",
    keyExports: ["memoTransformSettings"],
  },
  {
    id: "table-memo-transformations",
    layer: "shared",
    label: "memo_transformations",
    path: "apps/dashboard/src/shared/lib/db/schema/memo.ts",
    symbol: "memoTransformations",
    role: "메모 변환본(요약·할일 등) 테이블 — memo_id FK. 검색이 content 필드를 exists() 상관 서브쿼리로 함께 매칭한다.",
    keyExports: ["memoTransformations"],
    dependsOn: ["table-memos"],
  },
  {
    id: "table-memo-weekly-digests",
    layer: "shared",
    label: "memo_digests (table)",
    path: "apps/dashboard/src/shared/lib/db/schema/memo.ts",
    symbol: "memoDigests",
    role: "주간 다이제스트 저장 테이블 — week_end(일요일 KST 날짜), summary, memo_count, resurfaced_memo_ids 스냅샷 보관.",
    keyExports: ["memoDigests"],
    warning: "🔑 실제 테이블명은 memo_digests (힌트의 memo_weekly_digests 아님). unique index memo_digests_user_week_uq on (user_id, week_end)가 멱등 키 — memo_count=0이면 summary=''로 빈 주 marker.",
  },
  {
    id: "table-memos",
    layer: "shared",
    label: "memos",
    path: "apps/dashboard/src/shared/lib/db/schema/memo.ts",
    symbol: "memos",
    role: "텍스트/음성 메모 테이블. 이 흐름에서는 listDueReminders가 push body(⏰ 알림 본문)에 쓸 title을 JOIN으로 가져오는 출처.",
    keyExports: ["memos"],
    dependsOn: ["table-memo-categories"],
    warning: "category FK: references memo_categories.id onDelete 'set null'. 그래서 setMemoCategory 전에 upsertCategory 로 태그가 존재해야 함",
  },
  {
    id: "table-push-subscriptions",
    layer: "shared",
    label: "push_subscriptions",
    path: "apps/dashboard/src/shared/lib/db/schema/push.ts",
    symbol: "pushSubscriptions",
    role: "웹 푸시 구독(endpoint/p256dh/auth) 테이블. sendPushToUser가 userId로 조회해 발송, 만료 구독은 DELETE로 정리.",
    keyExports: ["pushSubscriptions"],
  },
  {
    id: "transform-buildTransformSystemPrompt",
    layer: "features",
    label: "buildTransformSystemPrompt",
    path: "apps/dashboard/src/features/memo-transform/lib/prompts.ts",
    symbol: "buildTransformSystemPrompt",
    role: "3층 프롬프트 조립(하드 계약+충실 가드+프리셋별 스타일 지시) — server-only로 client 번들 격리",
    keyExports: ["buildTransformSystemPrompt","PRESET_INSTRUCTIONS","HARD_CONTRACT","FIDELITY_GUARD"],
  },
  {
    id: "transform-listPresetCatalog",
    layer: "features",
    label: "listPresetCatalog",
    path: "apps/dashboard/src/features/memo-transform/lib/preset-resolver.ts",
    symbol: "listPresetCatalog",
    role: "사용자 프리셋 목록(빌트인 7종+커스텀)을 병합해 페이지에 카탈로그로 제공",
    keyExports: ["listPresetCatalog"],
    dependsOn: ["memo-listPresetsByUser"],
  },
  {
    id: "transform-preset-meta",
    layer: "features",
    label: "TRANSFORM_PRESETS",
    path: "apps/dashboard/src/features/memo-transform/lib/preset-meta.ts",
    symbol: "TRANSFORM_PRESETS",
    role: "프리셋별 client-safe 메타(minInputLen, strictPreserve) — 프롬프트 비노출",
    keyExports: ["TRANSFORM_PRESETS","isTransformPresetId","TransformPresetMeta"],
  },
  {
    id: "transform-resolveMemoModelSelection",
    layer: "features",
    label: "resolveMemoModelSelection",
    path: "apps/dashboard/src/features/memo-transform/lib/model-registry.ts",
    symbol: "resolveMemoModelSelection",
    role: "DB 모델 키(claude/codex/gemini)를 cli-proxy가 라우팅할 실제 모델 ID로 변환 — modelId null이면 provider별 env 기본값",
    keyExports: ["resolveMemoModelSelection","resolveMemoModelId"],
  },
  {
    id: "transform-resolvePreset",
    layer: "features",
    label: "resolvePreset",
    path: "apps/dashboard/src/features/memo-transform/lib/preset-resolver.ts",
    symbol: "resolvePreset",
    role: "slug→ResolvedPreset 해석 — 빌트인/커스텀/override 병합 + 모델 선택(preset.model 또는 getDefaultMemoModel 상속) 결정",
    keyExports: ["resolvePreset","listPresetCatalog","mergePresetCatalog","resolveDefaultMemoModel","ResolvedPreset"],
    dependsOn: ["memo-getDefaultMemoModel","memo-getPresetBySlug","transform-resolveMemoModelSelection"],
    warning: "변환 모델은 고정 상수 아님 — row.model 있으면 preset override, 없으면 사용자 기본 모델(defaultModel) 상속",
  },
  {
    id: "transform-saveTransformationAction",
    layer: "features",
    label: "saveTransformationAction",
    path: "apps/dashboard/src/features/memo-transform/api/saveTransformationAction.ts",
    symbol: "saveTransformationAction",
    role: "미리보기에서 편집됐을 수 있는 content를 승인 저장하는 Server Action — 같은 preset은 교체",
    keyExports: ["saveTransformationAction","SaveTransformationResult"],
    dependsOn: ["memo-getMemo","memo-upsertTransformation","transform-resolvePreset"],
    warning: "모델은 고정 상수 아님 — resolved.modelId(preset.modelId 또는 기본 모델 상속)를 감사용으로 함께 저장",
  },
  {
    id: "transform-TransformDialog",
    layer: "features",
    label: "TransformDialog",
    path: "apps/dashboard/src/features/memo-transform/ui/TransformDialog.tsx",
    symbol: "TransformDialog",
    role: "user가 프리셋을 선택→미리보기→편집→승인하는 3-phase(pick/loading/preview) 클라이언트 다이얼로그",
    keyExports: ["TransformDialog"],
    dependsOn: ["transform-saveTransformationAction","transform-transformMemoAction"],
    warning: "createPortal로 body 탈출 필수 — inert 조상 아래 렌더되면 클릭 불가(과거 사고)",
  },
  {
    id: "transform-transformMemoAction",
    layer: "features",
    label: "transformMemoAction",
    path: "apps/dashboard/src/features/memo-transform/api/transformMemoAction.ts",
    symbol: "transformMemoAction",
    role: "미리보기 생성 Server Action — DB 쓰기 없이 프리셋 해석 후 LLM 변환 결과만 반환",
    keyExports: ["transformMemoAction","TransformMemoResult"],
    dependsOn: ["memo-getMemo","transform-resolvePreset","transform-transformMemoContent"],
    warning: "\"use server\" 파일에서 import한 타입 재-export 금지(ReferenceError). 결과 타입은 파일 내 선언만",
  },
  {
    id: "transform-transformMemoContent",
    layer: "features",
    label: "transformMemoContent",
    path: "apps/dashboard/src/features/memo-transform/lib/transform-memo.ts",
    symbol: "transformMemoContent",
    role: "ResolvedPreset로 3층 시스템 프롬프트 조립 후 analyzeStructured(LLM) 호출 — refusal/degenerate/empty 검사",
    keyExports: ["transformMemoContent","TransformResponseSchema","TransformOutcome"],
    dependsOn: ["shared-analyzeStructured","transform-buildTransformSystemPrompt"],
    warning: "온디맨드+미리보기 승인 흐름이라 raw-fallback 저장 없음 — 실패는 failed로 반환만. 관측(logLlmSpend)은 best-effort로 결과 안 뒤집음",
  },
  {
    id: "widget-memo",
    layer: "widgets",
    label: "MemoWidget",
    path: "apps/dashboard/src/widgets/memo/ui/MemoWidget.tsx",
    symbol: "MemoWidget",
    role: "메모 조합 위젯 — MemoComposer + SearchableMemoList 를 감싸고 memos·categories 등 props 를 그대로 전달.",
    keyExports: ["MemoWidget"],
    dependsOn: ["compose-MemoComposer","search-SearchableMemoList","transform-TransformDialog"],
  },
  ],
  flows: [
  {
    id: "write-path",
    label: "작성→저장→백그라운드",
    summary: "음성/텍스트 메모를 AI 정리 후 승인 저장, after()로 분류·액션추출 백그라운드 킥",
    triggers: ["user","after"],
    llm: {"model":"claude-sonnet-5","touchpoint":"받아쓰기 정리(cleanup)"},
    async: true,
    idempotencyKey: null,
    nodeIds: ["page-memos","widget-memo","compose-MemoComposer","compose-cleanupTranscript","compose-createMemoAction","memo-createMemo","table-memos","classify-classifyAndPersistMemoCategory","actions-extractAndPersistMemoActions"],
    edges: [
      { from: "page-memos", to: "widget-memo", label: "render" },
      { from: "widget-memo", to: "compose-MemoComposer", label: "render" },
      { from: "compose-MemoComposer", to: "compose-createMemoAction", label: "call (승인 저장)" },
      { from: "compose-createMemoAction", to: "memo-createMemo", label: "call" },
      { from: "memo-createMemo", to: "table-memos", label: "INSERT" },
      { from: "compose-createMemoAction", to: "classify-classifyAndPersistMemoCategory", label: "after() / allSettled" },
      { from: "compose-createMemoAction", to: "actions-extractAndPersistMemoActions", label: "after() / allSettled" }
    ],
  },
  {
    id: "auto-classify",
    label: "자동 분류",
    summary: "미분류 메모를 Haiku로 카테고리 태깅. after() 즉시경로 + memo-classify cron sweep 폴백",
    triggers: ["after","cron"],
    llm: {"model":"HAIKU_MODEL","touchpoint":"카테고리 분류"},
    async: true,
    idempotencyKey: "category IS NULL",
    nodeIds: ["cron-memo-classify","classify-classifyAndPersistMemoCategory","classify-upsertCategory","memo-setMemoCategory","anthropic-HAIKU_MODEL","table-memos","table-memo-categories"],
    edges: [
      { from: "cron-memo-classify", to: "classify-classifyAndPersistMemoCategory", label: "perTarget (concurrency 2)" },
      { from: "classify-classifyAndPersistMemoCategory", to: "classify-upsertCategory", label: "1) upsert (FK 선등록)" },
      { from: "classify-classifyAndPersistMemoCategory", to: "memo-setMemoCategory", label: "2) UPDATE category" },
      { from: "classify-upsertCategory", to: "table-memo-categories", label: "INSERT onConflictDoNothing" },
      { from: "memo-setMemoCategory", to: "table-memos", label: "UPDATE category" },
      { from: "table-memos", to: "table-memo-categories", label: "FK category → id (set null)" }
    ],
  },
  {
    id: "transform-preset",
    label: "변환(프리셋)",
    summary: "프리셋 지시로 메모를 재작성. 미리보기→승인 후 upsertTransformation. 모델은 프리셋 override 또는 기본 모델 상속",
    triggers: ["user"],
    llm: {"model":"프리셋 모델","touchpoint":"메모 변환"},
    async: false,
    idempotencyKey: null,
    nodeIds: ["page-memos","widget-memo","transform-TransformDialog","transform-transformMemoAction","transform-resolvePreset","transform-saveTransformationAction","memo-upsertTransformation","shared-analyzeStructured","table-memo-transformations","table-memo-transform-presets"],
    edges: [
      { from: "page-memos", to: "widget-memo", label: "render (presets/transformations 주입)" },
      { from: "widget-memo", to: "transform-TransformDialog", label: "render (SearchableMemoList→MemoList 경유)" },
      { from: "transform-TransformDialog", to: "transform-transformMemoAction", label: "call (미리보기 생성)" },
      { from: "transform-TransformDialog", to: "transform-saveTransformationAction", label: "call (승인 저장)" },
      { from: "transform-transformMemoAction", to: "transform-resolvePreset", label: "call (slug→ResolvedPreset)" },
      { from: "transform-saveTransformationAction", to: "transform-resolvePreset", label: "call (라벨·modelId 확정)" },
      { from: "transform-saveTransformationAction", to: "memo-upsertTransformation", label: "call (승인 저장)" },
      { from: "memo-upsertTransformation", to: "table-memo-transformations", label: "INSERT ... onConflictDoUpdate" }
    ],
  },
  {
    id: "extract-actions",
    label: "액션 추출",
    summary: "메모에서 할일·일정을 Sonnet으로 추출. after() 즉시경로 + 48h 창 memo-extract-actions cron. claim-first 삽입",
    triggers: ["after","cron"],
    llm: {"model":"claude-sonnet-5","touchpoint":"할일·일정 추출"},
    async: true,
    idempotencyKey: "actionsExtractedAt claim-first",
    nodeIds: ["cron-memo-extract-actions","actions-extractAndPersistMemoActions","actions-insertActionItemsAndMark","memo-listMemosNeedingExtraction","table-memos","table-memo-action-items"],
    edges: [
      { from: "cron-memo-extract-actions", to: "memo-listMemosNeedingExtraction", label: "targetSelect (48h/limit 50)" },
      { from: "cron-memo-extract-actions", to: "actions-extractAndPersistMemoActions", label: "perTarget" },
      { from: "memo-listMemosNeedingExtraction", to: "table-memos", label: "SELECT (IS NULL + gte since)" },
      { from: "actions-extractAndPersistMemoActions", to: "actions-insertActionItemsAndMark", label: "claim-first insert" },
      { from: "actions-insertActionItemsAndMark", to: "table-memos", label: "UPDATE actions_extracted_at (IS NULL claim)" },
      { from: "actions-insertActionItemsAndMark", to: "table-memo-action-items", label: "INSERT" },
      { from: "table-memo-action-items", to: "table-memos", label: "FK memo_id" }
    ],
  },
  {
    id: "action-transition",
    label: "액션 상태 전이",
    summary: "제안된 액션을 수락/무시/완료로 전이. ACTION_ITEM_ALLOWED_FROM 상태기계 검증, no-LLM",
    triggers: ["user"],
    llm: null,
    async: false,
    idempotencyKey: null,
    nodeIds: ["page-memos","actions-MemoActionPanel","actions-updateActionItemStatusAction","repo-updateActionItemStatus","memo-actionItem-stateMachine","table-memo-action-items"],
    edges: [
      { from: "actions-MemoActionPanel", to: "actions-updateActionItemStatusAction", label: "onClick 호출" },
      { from: "actions-updateActionItemStatusAction", to: "repo-updateActionItemStatus", label: "call" },
      { from: "actions-updateActionItemStatusAction", to: "page-memos", label: "revalidatePath('/memos')" },
      { from: "repo-updateActionItemStatus", to: "memo-actionItem-stateMachine", label: "ACTION_ITEM_ALLOWED_FROM[to] 조회" },
      { from: "repo-updateActionItemStatus", to: "table-memo-action-items", label: "UPDATE WHERE(id+userId+status inArray)" },
      { from: "memo-actionItem-stateMachine", to: "table-memo-action-items", label: "동기 대상 (status CHECK)" }
    ],
  },
  {
    id: "action-reminder",
    label: "기한 리마인더",
    summary: "기한 도래한 accepted 액션에 push 발송. remindedAt claim으로 무한 재시도 차단, no-LLM",
    triggers: ["cron"],
    llm: null,
    async: false,
    idempotencyKey: "remindedAt",
    nodeIds: ["scheduler-memo-action-reminders","cron-memo-action-reminders","action-remindDueActionItem","action-listDueReminders","action-markActionItemReminded","shared-sendPushToUser","table-memo-action-items","table-push-subscriptions"],
    edges: [
      { from: "scheduler-memo-action-reminders", to: "cron-memo-action-reminders", label: "HTTP POST (37 * * * * KST)" },
      { from: "cron-memo-action-reminders", to: "action-listDueReminders", label: "targetSelect()" },
      { from: "cron-memo-action-reminders", to: "action-remindDueActionItem", label: "perTarget()" },
      { from: "action-listDueReminders", to: "table-memo-action-items", label: "SELECT WHERE accepted+due+remindedAt IS NULL" },
      { from: "action-remindDueActionItem", to: "shared-sendPushToUser", label: "push 발송" },
      { from: "action-remindDueActionItem", to: "action-markActionItemReminded", label: "별도 try (best-effort)" },
      { from: "shared-sendPushToUser", to: "table-push-subscriptions", label: "SELECT / DELETE(만료)" },
      { from: "action-markActionItemReminded", to: "table-memo-action-items", label: "UPDATE remindedAt" }
    ],
  },
  {
    id: "weekly-digest",
    label: "주간 다이제스트",
    summary: "주간 메모를 Sonnet으로 요약 + 누락 주 백필(오래된 순 컷). 매일 19:05 cron",
    triggers: ["cron"],
    llm: {"model":"claude-sonnet-5","touchpoint":"주간 요약"},
    async: true,
    idempotencyKey: "unique(user_id, week_end)",
    nodeIds: ["cron-memo-digest","digest-generateWeeklyDigest","digest-enumerateMissingWeekEnds","digest-insertDigest","shared-analyzeStructured","shared-sendPushToUser","table-memos","table-memo-weekly-digests"],
    edges: [
      { from: "cron-memo-digest", to: "digest-generateWeeklyDigest", label: "perTarget(userId)" },
      { from: "digest-generateWeeklyDigest", to: "digest-enumerateMissingWeekEnds", label: "누락 주 열거(오래된 순 컷)" },
      { from: "digest-generateWeeklyDigest", to: "shared-analyzeStructured", label: "summarizeWeek() Sonnet 호출" },
      { from: "digest-generateWeeklyDigest", to: "digest-insertDigest", label: "멱등 INSERT (LLM 성공 후)" },
      { from: "digest-generateWeeklyDigest", to: "shared-sendPushToUser", label: "push (최신 주만, best-effort)" },
      { from: "digest-insertDigest", to: "table-memo-weekly-digests", label: "INSERT onConflictDoNothing" }
    ],
  },
  {
    id: "search-filter",
    label: "검색+필터",
    summary: "ILIKE 다중필드 검색 + 카테고리 필터. SEARCH_MEMOS_LIMIT+1로 절단 판별, 읽기전용 no-LLM",
    triggers: ["user"],
    llm: null,
    async: false,
    idempotencyKey: null,
    nodeIds: ["page-memos","widget-memo","search-SearchableMemoList","search-searchMemosAction","memoRepo-searchMemos","search-tokenizeSearchQuery","table-memos","table-memo-categories"],
    edges: [
      { from: "page-memos", to: "widget-memo", label: "render(props 주입)" },
      { from: "widget-memo", to: "search-SearchableMemoList", label: "render" },
      { from: "search-SearchableMemoList", to: "search-searchMemosAction", label: "call(300ms 디바운스)" },
      { from: "search-SearchableMemoList", to: "search-tokenizeSearchQuery", label: "call(하이라이트 토큰)" },
      { from: "search-searchMemosAction", to: "memoRepo-searchMemos", label: "call(auth 후 위임)" },
      { from: "memoRepo-searchMemos", to: "search-tokenizeSearchQuery", label: "call(토큰화·escapeLike)" },
      { from: "memoRepo-searchMemos", to: "table-memos", label: "SELECT ILIKE(title·raw·cleaned)" },
      { from: "table-memos", to: "table-memo-categories", label: "FK(category→id, set null)" }
    ],
  },
  ],
  maintenance: [
  {
    task: "메모 cron 4종 로컬 수동 트리거",
    where: "app/api/cron/{memo-classify,memo-digest,memo-extract-actions,memo-action-reminders}/route.ts",
    how: "각 cron을 로컬 dev 서버에 POST. 토큰 불일치 시 401.",
    command: "curl -X POST http://localhost:3020/api/cron/memo-classify         -H \"Authorization: Bearer $CRON_BEARER_TOKEN\"\ncurl -X POST http://localhost:3020/api/cron/memo-digest           -H \"Authorization: Bearer $CRON_BEARER_TOKEN\"\ncurl -X POST http://localhost:3020/api/cron/memo-extract-actions  -H \"Authorization: Bearer $CRON_BEARER_TOKEN\"\ncurl -X POST http://localhost:3020/api/cron/memo-action-reminders -H \"Authorization: Bearer $CRON_BEARER_TOKEN\"",
  },
  {
    task: "분류 프롬프트·토큰 수정",
    where: "classifyMemo.ts:buildSystemPrompt / classifyMemoContent",
    how: "시스템 프롬프트 템플릿을 편집. 응답 스키마(MemoCategoryResponseSchema)에 slug regex를 넣지 말 것 — 파싱 뒤 isValidCategorySlug로 검증한다.",
    command: "pnpm typecheck && pnpm lint",
    warning: "MemoCategoryResponseSchema에 slug regex 금지 — 스키마 throw가 llm-unavailable로 잡혀 etc fallback 미도달→무한 미분류 (커밋 5699622).",
  },
  {
    task: "새 카테고리 태그 추가(코드 없이)",
    where: "memo_categories 테이블 (마이그레이션 0044 참조)",
    how: "참조 테이블에 행 INSERT. memos.category가 FK로 참조하므로 코드 배포 없이 태그가 늘어난다.",
    command: "psql \"$DATABASE_URL\" -c \"INSERT INTO memo_categories (id,label_ko,is_seed) VALUES ('meeting-log','회의록',false) ON CONFLICT DO NOTHING;\"",
  },
  {
    task: "고정 상수 LLM 작업 모델 변경(정리·분류·추출·다이제스트)",
    where: "cleanup-transcript.ts:CLEANUP_MODEL / anthropic.ts:HAIKU_MODEL / extractMemoActions.ts:EXTRACT_MODEL / generateWeeklyDigest.ts:DIGEST_MODEL",
    how: "각 파일의 모델 상수를 직접 교체. 생성 계열(정리·추출·다이제스트)은 haiku 금지(이메일 초안 거절 전례).",
    command: "cd apps/dashboard && pnpm build",
    warning: "HAIKU_MODEL은 메모 전용이 아니다 — shared/lib/llm/anthropic.ts의 공유 상수라 메모 분류뿐 아니라 이메일 답장 분류(classify-thread.ts)·중요도 분류(classify-important.ts)도 함께 쓴다. 이 상수를 바꾸면 이메일 분류 모델까지 바뀐다. 메모만 독립 변경하려면 MEMO_CLASSIFY_MODEL을 분리해 classifyMemo.ts만 참조하게 할 것.",
  },
  {
    task: "변환(transform) 모델 변경 — 상수 아님, 프리셋 경유",
    where: "features/memo-transform/lib/preset-resolver.ts:resolvePreset / transform-memo.ts",
    how: "변환은 고정 상수가 없다. 사용자 프리셋 모델(memo_transform_presets.model/model_id)을 우선 사용하고, 미지정이면 getDefaultMemoModel을 상속한다. 기본값·폴백은 /memos/settings 또는 env MEMO_LLM_MODEL_{CLAUDE,CODEX,GEMINI}.",
    command: "cd apps/dashboard && pnpm build",
  },
  {
    task: "새 빌트인 프리셋 추가",
    where: "entities/memo/model/types.ts (TRANSFORM_PRESET_IDS + TRANSFORM_PRESET_LABELS) / features/memo-transform/lib/prompts.ts (PRESET_INSTRUCTIONS) / features/memo-transform/lib/preset-meta.ts (TRANSFORM_PRESETS)",
    how: "3개 파일, 4개 정의를 함께 갱신. Record 타입이라 하나 빠뜨리면 tsc가 잡는다.",
    command: "pnpm typecheck",
  },
  {
    task: "액션 상태기계 수정",
    where: "actionItem.ts:ACTION_ITEM_ALLOWED_FROM",
    how: "허용 전이 맵을 편집. DB CHECK(memo_action_items_status_check)와 반드시 동기 유지.",
    command: "pnpm typecheck && pnpm test",
    warning: "DB CHECK·fixture 동기 — 상태 추가 시 스키마 CHECK와 테스트 fixture를 전수 grep해 함께 갱신할 것.",
  },
  {
    task: "다이제스트 백필·주차경계·재부상",
    where: "week.ts:enumerateMissingWeekEnds",
    how: "누락 주 열거 로직을 편집. 오래된 순(reverse 후 slice) 컷을 유지할 것.",
    command: "pnpm test",
    warning: "오래된 순 컷 유지 (PR #297) — 최신 우선이면 커서가 4주 초과 공백의 잔여 주를 영구 스킵한다.",
  },
  {
    task: "cron 스케줄 변경",
    where: "apps/cron/scheduler.js (crontab 문자열 + 하단 콘솔 로그 동기)",
    how: "cron 컨테이너는 Docker로만 빌드(GHA가 apps/cron 컨텍스트로 이미지 푸시)라 로컬 pnpm으로 안 돌고, 이미지 빌드 + 운영 컨테이너 교체까지 해야 반영된다. gh run watch는 빌드 대기일 뿐 — pull + up -d cron으로 실제 교체 필수.",
    command: "set -e\nCOMPOSE=\"/home/gon/projects/gon/gons-dashboard/docker-compose.yml\"\ngh run watch                                                       # GHA 이미지 빌드 완료 대기\ndocker --context home-server compose -f \"$COMPOSE\" pull cron       # 새 cron 이미지 받기\ndocker --context home-server compose -f \"$COMPOSE\" up -d cron      # 컨테이너 교체",
    warning: "gh run watch만으로는 미완성 — pull + up -d cron까지 해야 운영 반영.",
  },
  {
    task: "운영 DB 마이그레이션 선적용",
    where: "apps/dashboard/drizzle/00XX_*.sql (다음 순번)",
    how: "db:migrate가 운영 tracking을 인식 못 하므로 우회 필수. 새 마이그레이션 SQL을 psql -f로 트랜잭션 적용한 뒤 이미지 배포. 운영 daemon 대상은 반드시 docker --context home-server. psql에 -v ON_ERROR_STOP=1 필수. 운영 DB명은 gons_dashboard.",
    command: "set -e\nMIGRATION_FILE=\"apps/dashboard/drizzle/0045_new_migration.sql\"   # ← 실제 파일로 교체\ntest -f \"$MIGRATION_FILE\"                                         # 없으면 여기서 중단(fail-closed)\nREMOTE=\"/tmp/$(basename \"$MIGRATION_FILE\")\"                       # 고정 /tmp/mig.sql 재사용 사고 방지\ndocker --context home-server cp \"$MIGRATION_FILE\" \"gons-dashboard-postgres:$REMOTE\"\ndocker --context home-server exec gons-dashboard-postgres \\\n  psql -U gons -d gons_dashboard -v ON_ERROR_STOP=1 --single-transaction -f \"$REMOTE\"\ndocker --context home-server exec gons-dashboard-postgres rm -f \"$REMOTE\"",
    warning: "plain docker는 로컬 context(default) 대상 — 운영에 안 닿는다. --context home-server 명시 필수. ON_ERROR_STOP=1 없으면 SQL 오류에도 silent partial-apply.",
  },
  ],
};
